// Product data for the entire site
export interface Product {
  id: string;
  slug: string;
  name: string;
  category: string;
  categorySlug: string;
  price: number;
  mrp: number;
  discount: number;
  badge: string;
  rating: number;
  reviews: number;
  image: string;
  image2?: string;
  customizable: boolean;
  description: string;
  details: string;
  shipping: string;
}

export const IMAGES = {
  hero_main: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=1400&q=90",
  hero_float1: "https://images.unsplash.com/photo-1608848461950-0fe51dfc41cb?w=400&q=80",
  hero_float2: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&q=80",
  craft_process: "https://images.unsplash.com/photo-1594938298603-c8148c4b4571?w=900&q=85",
  about_hero: "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=900&q=85",
  about_story1: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&q=80",
  about_story2: "https://images.unsplash.com/photo-1607344645866-009c320b63e0?w=600&q=80",
  img_keychain: "https://images.unsplash.com/photo-1608848461950-0fe51dfc41cb?w=700&q=85",
  img_frame: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=700&q=85",
  img_wedding: "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=700&q=85",
  img_bookmark: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=700&q=85",
  img_coaster: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=700&q=85",
  img_hamper: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=700&q=85",
  img_tray: "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=700&q=85",
  img_tray2: "https://images.unsplash.com/photo-1594938298603-c8148c4b4571?w=700&q=85",
  img_wedding2: "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=700&q=85",
  img_keychain2: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=700&q=85",
  img_bookmark2: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=700&q=85",
  img_hamper2: "https://images.unsplash.com/photo-1607344645866-009c320b63e0?w=700&q=85",
  g1: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600&q=80",
  g2: "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=600&q=80",
  g3: "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=600&q=80",
  g4: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
  g5: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80",
  g6: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&q=80",
};

export const CATEGORIES = [
  { name: "Name Keychains", slug: "keychain", image: IMAGES.img_keychain },
  { name: "Photo Frames", slug: "frame", image: IMAGES.img_frame },
  { name: "Wedding Keepsakes", slug: "wedding", image: IMAGES.img_wedding },
  { name: "Bookmarks", slug: "bookmark", image: IMAGES.img_bookmark },
  { name: "Coaster Sets", slug: "coaster", image: IMAGES.img_coaster },
  { name: "Gift Hampers", slug: "hamper", image: IMAGES.img_hamper },
  { name: "Resin Trays", slug: "tray", image: IMAGES.img_tray },
];

export const products: Product[] = [
  {
    id: "1",
    slug: "personalized-name-keychain",
    name: "Personalized Name Keychain",
    category: "Name Keychains",
    categorySlug: "keychain",
    price: 499,
    mrp: 699,
    discount: 29,
    badge: "BESTSELLER",
    rating: 4.9,
    reviews: 128,
    image: IMAGES.img_keychain,
    customizable: true,
    description: "A stunning handmade resin keychain personalized with your name or loved one's name. Each piece features real dried flowers embedded in crystal-clear resin with gold leaf accents.",
    details: "Material: Premium UV-resistant resin with real dried flowers. Size: 5cm x 3cm. Finish: High-gloss with gold leaf details. Includes: Keychain ring + gift box.",
    shipping: "Ships within 5-7 business days. Free shipping on orders above ₹999. Pan India delivery available.",
  },
  {
    id: "2",
    slug: "couple-photo-frame",
    name: "Couple Photo Frame",
    category: "Photo Frames",
    categorySlug: "frame",
    price: 1299,
    mrp: 1799,
    discount: 28,
    badge: "POPULAR",
    rating: 4.8,
    reviews: 94,
    image: IMAGES.img_frame,
    customizable: true,
    description: "A beautifully crafted resin photo frame that preserves your special moment with real flowers and personalized details. Perfect for couples, anniversaries, and special occasions.",
    details: "Material: Premium resin with real preserved flowers. Size: 8x10 inches. Includes: Frame stand + gift wrapping.",
    shipping: "Ships within 5-7 business days. Free shipping on orders above ₹999. Pan India delivery available.",
  },
  {
    id: "3",
    slug: "bridal-bouquet-preservation",
    name: "Bridal Bouquet Preservation",
    category: "Wedding Keepsakes",
    categorySlug: "wedding",
    price: 2499,
    mrp: 3499,
    discount: 29,
    badge: "PREMIUM",
    rating: 4.9,
    reviews: 67,
    image: IMAGES.img_wedding,
    customizable: true,
    description: "Transform your bridal bouquet into a timeless keepsake. We preserve real wedding flowers in crystal-clear resin, creating a one-of-a-kind memory piece.",
    details: "Material: Premium crystal-clear resin. Size: Custom based on bouquet. Process: 3-4 weeks for preservation. Includes: Premium gift box + certificate.",
    shipping: "Ships within 3-4 weeks after receiving flowers. Free shipping. Pan India delivery.",
  },
  {
    id: "4",
    slug: "floral-resin-bookmark",
    name: "Floral Resin Bookmark",
    category: "Bookmarks",
    categorySlug: "bookmark",
    price: 349,
    mrp: 499,
    discount: 30,
    badge: "NEW",
    rating: 4.7,
    reviews: 45,
    image: IMAGES.img_bookmark,
    customizable: true,
    description: "A delicate handmade bookmark with real pressed flowers preserved in crystal-clear resin. Makes every reading session a little more special.",
    details: "Material: Clear resin with real pressed flowers. Size: 12cm x 3cm. Finish: Smooth polished edges. Includes: Gift sleeve.",
    shipping: "Ships within 5-7 business days. Free shipping on orders above ₹999. Pan India delivery available.",
  },
  {
    id: "5",
    slug: "ocean-resin-coaster-set",
    name: "Ocean Resin Coaster Set (4pc)",
    category: "Coaster Sets",
    categorySlug: "coaster",
    price: 899,
    mrp: 1199,
    discount: 25,
    badge: "POPULAR",
    rating: 4.8,
    reviews: 82,
    image: IMAGES.img_coaster,
    customizable: false,
    description: "A set of 4 stunning ocean-inspired resin coasters. Each coaster features beautiful blue and white swirl patterns reminiscent of ocean waves.",
    details: "Material: Premium resin with ocean pigments. Size: 10cm diameter each. Set includes: 4 coasters + cork backing + gift box.",
    shipping: "Ready to ship within 2-3 business days. Free shipping on orders above ₹999. Pan India delivery available.",
  },
  {
    id: "6",
    slug: "luxury-gift-hamper",
    name: "Luxury Gift Hamper",
    category: "Gift Hampers",
    categorySlug: "hamper",
    price: 2999,
    mrp: 3749,
    discount: 20,
    badge: "PREMIUM",
    rating: 4.9,
    reviews: 38,
    image: IMAGES.img_hamper,
    customizable: true,
    description: "A premium curated gift hamper featuring a selection of handcrafted resin pieces. Perfect for birthdays, weddings, and corporate gifting.",
    details: "Contents: 1 name keychain + 1 bookmark + 2 coasters + 1 mini tray. All pieces customizable. Premium packaging with ribbon.",
    shipping: "Ships within 7-10 business days. Free shipping included. Pan India delivery available.",
  },
  {
    id: "7",
    slug: "floral-heart-resin-tray",
    name: "Floral Heart Resin Tray",
    category: "Resin Trays",
    categorySlug: "tray",
    price: 1199,
    mrp: 1549,
    discount: 22,
    badge: "BESTSELLER",
    rating: 4.9,
    reviews: 103,
    image: IMAGES.img_tray,
    customizable: true,
    description: "A gorgeous heart-shaped resin tray adorned with real dried flowers and gold leaf. Perfect as a jewelry tray, vanity organizer, or decorative piece.",
    details: "Material: Premium resin with real flowers and gold leaf. Size: 15cm heart shape. Includes: Gift box + care card.",
    shipping: "Ships within 5-7 business days. Free shipping on orders above ₹999. Pan India delivery available.",
  },
  {
    id: "8",
    slug: "custom-name-resin-tray",
    name: "Custom Name Resin Tray",
    category: "Resin Trays",
    categorySlug: "tray",
    price: 1499,
    mrp: 1799,
    discount: 18,
    badge: "POPULAR",
    rating: 4.7,
    reviews: 56,
    image: IMAGES.img_tray2,
    customizable: true,
    description: "A personalized resin tray featuring your name or initials in elegant gold lettering, surrounded by real pressed flowers and botanical elements.",
    details: "Material: Premium resin with real flowers and gold lettering. Size: 20cm round. Includes: Gift box + care card.",
    shipping: "Ships within 5-7 business days. Free shipping on orders above ₹999. Pan India delivery available.",
  },
  {
    id: "9",
    slug: "wedding-memory-frame",
    name: "Wedding Memory Frame",
    category: "Wedding Keepsakes",
    categorySlug: "wedding",
    price: 1899,
    mrp: 2499,
    discount: 25,
    badge: "BESTSELLER",
    rating: 4.9,
    reviews: 71,
    image: IMAGES.img_wedding2,
    customizable: true,
    description: "Preserve your wedding memories in a stunning resin frame. Features real wedding flowers, names, and dates embedded in crystal-clear resin.",
    details: "Material: Premium resin with preserved wedding flowers. Size: 10x12 inches. Includes: Frame stand + premium gift box.",
    shipping: "Ships within 2-3 weeks. Free shipping included. Pan India delivery.",
  },
  {
    id: "10",
    slug: "mini-keychains-bundle",
    name: "Mini Keychains Bundle (3pc)",
    category: "Name Keychains",
    categorySlug: "keychain",
    price: 999,
    mrp: 1499,
    discount: 35,
    badge: "NEW",
    rating: 4.8,
    reviews: 29,
    image: IMAGES.img_keychain2,
    customizable: true,
    description: "A bundle of 3 mini personalized keychains — perfect for gifting friends, bridesmaids, or family. Each keychain can have a different name.",
    details: "Material: Premium resin with dried flowers. Size: 4cm x 2.5cm each. Set includes: 3 keychains + individual gift pouches.",
    shipping: "Ships within 5-7 business days. Free shipping included. Pan India delivery available.",
  },
  {
    id: "11",
    slug: "dried-flower-bookmark-set",
    name: "Dried Flower Bookmark Set (3pc)",
    category: "Bookmarks",
    categorySlug: "bookmark",
    price: 699,
    mrp: 949,
    discount: 28,
    badge: "POPULAR",
    rating: 4.6,
    reviews: 44,
    image: IMAGES.img_bookmark2,
    customizable: false,
    description: "A set of 3 handmade bookmarks, each featuring different real dried flowers preserved in clear resin. A perfect gift for book lovers.",
    details: "Material: Clear resin with real dried flowers. Size: 12cm x 3cm each. Set includes: 3 bookmarks + gift sleeve.",
    shipping: "Ready to ship within 2-3 business days. Free shipping on orders above ₹999. Pan India delivery available.",
  },
  {
    id: "12",
    slug: "corporate-gift-box",
    name: "Corporate Gift Box",
    category: "Gift Hampers",
    categorySlug: "hamper",
    price: 3499,
    mrp: 4099,
    discount: 15,
    badge: "PREMIUM",
    rating: 4.8,
    reviews: 22,
    image: IMAGES.img_hamper2,
    customizable: true,
    description: "A premium corporate gift box with customizable resin pieces. Ideal for client gifting, employee appreciation, and corporate events. Bulk orders available.",
    details: "Contents: 2 coasters + 1 tray + 1 keychain (all brandable). Includes: Premium branded box + thank you card. MOQ: 5 boxes for bulk pricing.",
    shipping: "Ships within 10-14 business days for custom orders. Free shipping on bulk orders. Pan India delivery.",
  },
];

export const getProductBySlug = (slug: string) => products.find((p) => p.slug === slug);
export const getProductsByCategory = (cat: string) => cat === "all" ? products : products.filter((p) => p.categorySlug === cat);
export const getBestSellers = () => products.filter((p) => p.badge === "BESTSELLER" || p.badge === "POPULAR").slice(0, 4);

export const GALLERY_IMAGES = [
  { src: IMAGES.g1, alt: "Resin art piece", category: "tray" },
  { src: IMAGES.g2, alt: "Wedding keepsake", category: "wedding" },
  { src: IMAGES.g3, alt: "Wedding memory", category: "wedding" },
  { src: IMAGES.g4, alt: "Ocean coasters", category: "coaster" },
  { src: IMAGES.g5, alt: "Gift hamper", category: "hamper" },
  { src: IMAGES.g6, alt: "Bookmark collection", category: "bookmark" },
  { src: IMAGES.img_keychain, alt: "Name keychain", category: "keychain" },
  { src: IMAGES.img_frame, alt: "Photo frame", category: "frame" },
  { src: IMAGES.img_wedding, alt: "Wedding flowers", category: "wedding" },
  { src: IMAGES.img_tray, alt: "Floral tray", category: "tray" },
  { src: IMAGES.img_bookmark, alt: "Resin bookmark", category: "bookmark" },
  { src: IMAGES.img_hamper, alt: "Luxury hamper", category: "hamper" },
];
